// Mocks generated by Mockito 5.4.2 from annotations
// in tactical_e_clipboard/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:ui' as _i17;

import 'package:flutter/material.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:stacked_services/stacked_services.dart' as _i14;
import 'package:tactical_e_clipboard/model/config_model.dart' as _i11;
import 'package:tactical_e_clipboard/model/formation_model.dart' as _i5;
import 'package:tactical_e_clipboard/model/palyer_contract_model.dart' as _i13;
import 'package:tactical_e_clipboard/model/pattern_of_play_model.dart' as _i9;
import 'package:tactical_e_clipboard/model/player_model.dart' as _i3;
import 'package:tactical_e_clipboard/model/team_model.dart' as _i7;
import 'package:tactical_e_clipboard/repository/config_repository_impl.dart'
    as _i10;
import 'package:tactical_e_clipboard/repository/formation_repository_impl.dart'
    as _i4;
import 'package:tactical_e_clipboard/repository/pattern_of_play_repository_impl.dart'
    as _i8;
import 'package:tactical_e_clipboard/repository/player_contract_repository_impl.dart'
    as _i12;
import 'package:tactical_e_clipboard/repository/player_repository_impl.dart'
    as _i2;
import 'package:tactical_e_clipboard/repository/team_repository_impl.dart'
    as _i6;
import 'package:tactical_e_clipboard/services/config_service.dart' as _i23;
import 'package:tactical_e_clipboard/services/formation_service.dart' as _i20;
import 'package:tactical_e_clipboard/services/pattern_of_play_service.dart'
    as _i22;
import 'package:tactical_e_clipboard/services/player_contract_service.dart'
    as _i24;
import 'package:tactical_e_clipboard/services/player_service.dart' as _i18;
import 'package:tactical_e_clipboard/services/team_service.dart' as _i21;
import 'package:uuid/uuid.dart' as _i19;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlayerRepositoryImpl_0 extends _i1.SmartFake
    implements _i2.PlayerRepositoryImpl {
  _FakePlayerRepositoryImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerModel_1 extends _i1.SmartFake implements _i3.PlayerModel {
  _FakePlayerModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormationRepositoryImpl_2 extends _i1.SmartFake
    implements _i4.FormationRepositoryImpl {
  _FakeFormationRepositoryImpl_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFormationModel_3 extends _i1.SmartFake
    implements _i5.FormationModel {
  _FakeFormationModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamRepositoryImpl_4 extends _i1.SmartFake
    implements _i6.TeamRepositoryImpl {
  _FakeTeamRepositoryImpl_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTeamModel_5 extends _i1.SmartFake implements _i7.TeamModel {
  _FakeTeamModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePatternOfPlayRepositoryImpl_6 extends _i1.SmartFake
    implements _i8.PatternOfPlayRepositoryImpl {
  _FakePatternOfPlayRepositoryImpl_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePatternOfPlayModel_7 extends _i1.SmartFake
    implements _i9.PatternOfPlayModel {
  _FakePatternOfPlayModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigRepositoryImpl_8 extends _i1.SmartFake
    implements _i10.ConfigRepositoryImpl {
  _FakeConfigRepositoryImpl_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigModel_9 extends _i1.SmartFake implements _i11.ConfigModel {
  _FakeConfigModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerContractRepositoryImpl_10 extends _i1.SmartFake
    implements _i12.PlayerContractRepositoryImpl {
  _FakePlayerContractRepositoryImpl_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlayerContractModel_11 extends _i1.SmartFake
    implements _i13.PlayerContractModel {
  _FakePlayerContractModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i1.Mock implements _i14.NavigationService {
  @override
  String get previousRoute => (super.noSuchMethod(
        Invocation.getter(#previousRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  String get currentRoute => (super.noSuchMethod(
        Invocation.getter(#currentRoute),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i15.GlobalKey<_i15.NavigatorState>? nestedNavigationKey(int? index) =>
      (super.noSuchMethod(
        Invocation.method(
          #nestedNavigationKey,
          [index],
        ),
        returnValueForMissingStub: null,
      ) as _i15.GlobalKey<_i15.NavigatorState>?);
  @override
  void config({
    bool? enableLog,
    bool? defaultPopGesture,
    bool? defaultOpaqueRoute,
    Duration? defaultDurationTransition,
    bool? defaultGlobalState,
    _i14.Transition? defaultTransitionStyle,
    String? defaultTransition,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #config,
          [],
          {
            #enableLog: enableLog,
            #defaultPopGesture: defaultPopGesture,
            #defaultOpaqueRoute: defaultOpaqueRoute,
            #defaultDurationTransition: defaultDurationTransition,
            #defaultGlobalState: defaultGlobalState,
            #defaultTransitionStyle: defaultTransitionStyle,
            #defaultTransition: defaultTransition,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<T?>? navigateWithTransition<T>(
    _i15.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i15.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i14.Transition? transitionClass,
    _i14.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? replaceWithTransition<T>(
    _i15.Widget? page, {
    bool? opaque,
    String? transition = r'',
    Duration? duration,
    bool? popGesture,
    int? id,
    _i15.Curve? curve,
    bool? fullscreenDialog = false,
    bool? preventDuplicates = true,
    _i14.Transition? transitionClass,
    _i14.Transition? transitionStyle,
    String? routeName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWithTransition,
          [page],
          {
            #opaque: opaque,
            #transition: transition,
            #duration: duration,
            #popGesture: popGesture,
            #id: id,
            #curve: curve,
            #fullscreenDialog: fullscreenDialog,
            #preventDuplicates: preventDuplicates,
            #transitionClass: transitionClass,
            #transitionStyle: transitionStyle,
            #routeName: routeName,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  bool back<T>({
    dynamic result,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #back,
          [],
          {
            #result: result,
            #id: id,
          },
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
  @override
  void popUntil(
    _i15.RoutePredicate? predicate, {
    int? id,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #popUntil,
          [predicate],
          {#id: id},
        ),
        returnValueForMissingStub: null,
      );
  @override
  void popRepeated(int? popTimes) => super.noSuchMethod(
        Invocation.method(
          #popRepeated,
          [popTimes],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<T?>? navigateTo<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i15.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateTo,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? navigateToView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
    bool? opaque,
    _i15.Curve? curve,
    Duration? duration,
    bool? fullscreenDialog = false,
    bool? popGesture,
    bool? preventDuplicates = true,
    _i14.Transition? transition,
    _i14.Transition? transitionStyle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #navigateToView,
          [view],
          {
            #arguments: arguments,
            #id: id,
            #opaque: opaque,
            #curve: curve,
            #duration: duration,
            #fullscreenDialog: fullscreenDialog,
            #popGesture: popGesture,
            #preventDuplicates: preventDuplicates,
            #transition: transition,
            #transitionStyle: transitionStyle,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? replaceWith<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
    _i15.RouteTransitionsBuilder? transition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceWith,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
            #transition: transition,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearStackAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearStackAndShowView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearStackAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearTillFirstAndShow<T>(
    String? routeName, {
    dynamic arguments,
    int? id,
    bool? preventDuplicates = true,
    Map<String, String>? parameters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShow,
          [routeName],
          {
            #arguments: arguments,
            #id: id,
            #preventDuplicates: preventDuplicates,
            #parameters: parameters,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? clearTillFirstAndShowView<T>(
    _i15.Widget? view, {
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearTillFirstAndShowView,
          [view],
          {
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
  @override
  _i16.Future<T?>? pushNamedAndRemoveUntil<T>(
    String? routeName, {
    _i15.RoutePredicate? predicate,
    dynamic arguments,
    int? id,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushNamedAndRemoveUntil,
          [routeName],
          {
            #predicate: predicate,
            #arguments: arguments,
            #id: id,
          },
        ),
        returnValueForMissingStub: null,
      ) as _i16.Future<T?>?);
}

/// A class which mocks [BottomSheetService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetService extends _i1.Mock
    implements _i14.BottomSheetService {
  @override
  void setCustomSheetBuilders(Map<dynamic, _i14.SheetBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #setCustomSheetBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<_i14.SheetResponse<dynamic>?> showBottomSheet({
    required String? title,
    String? description,
    String? confirmButtonTitle = r'Ok',
    String? cancelButtonTitle,
    bool? enableDrag = true,
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showBottomSheet,
          [],
          {
            #title: title,
            #description: description,
            #confirmButtonTitle: confirmButtonTitle,
            #cancelButtonTitle: cancelButtonTitle,
            #enableDrag: enableDrag,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i16.Future<_i14.SheetResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i16.Future<_i14.SheetResponse<dynamic>?>.value(),
      ) as _i16.Future<_i14.SheetResponse<dynamic>?>);
  @override
  _i16.Future<_i14.SheetResponse<T>?> showCustomSheet<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i17.Color? barrierColor = const _i17.Color(2315255808),
    bool? barrierDismissible = true,
    bool? isScrollControlled = false,
    String? barrierLabel = r'',
    dynamic customData,
    R? data,
    bool? enableDrag = true,
    Duration? exitBottomSheetDuration,
    Duration? enterBottomSheetDuration,
    bool? ignoreSafeArea,
    bool? useRootNavigator = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomSheet,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #isScrollControlled: isScrollControlled,
            #barrierLabel: barrierLabel,
            #customData: customData,
            #data: data,
            #enableDrag: enableDrag,
            #exitBottomSheetDuration: exitBottomSheetDuration,
            #enterBottomSheetDuration: enterBottomSheetDuration,
            #ignoreSafeArea: ignoreSafeArea,
            #useRootNavigator: useRootNavigator,
          },
        ),
        returnValue: _i16.Future<_i14.SheetResponse<T>?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.SheetResponse<T>?>.value(),
      ) as _i16.Future<_i14.SheetResponse<T>?>);
  @override
  void completeSheet(_i14.SheetResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeSheet,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DialogService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDialogService extends _i1.Mock implements _i14.DialogService {
  @override
  void registerCustomDialogBuilders(
          Map<dynamic, _i14.DialogBuilder>? builders) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilders,
          [builders],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void registerCustomDialogBuilder({
    required dynamic variant,
    required _i15.Widget Function(
      _i15.BuildContext,
      _i14.DialogRequest<dynamic>,
      dynamic Function(_i14.DialogResponse<dynamic>),
    )? builder,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerCustomDialogBuilder,
          [],
          {
            #variant: variant,
            #builder: builder,
          },
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i16.Future<_i14.DialogResponse<dynamic>?> showDialog({
    String? title,
    String? description,
    String? cancelTitle,
    _i17.Color? cancelTitleColor,
    String? buttonTitle = r'Ok',
    _i17.Color? buttonTitleColor,
    bool? barrierDismissible = false,
    _i14.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #buttonTitle: buttonTitle,
            #buttonTitleColor: buttonTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i16.Future<_i14.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i16.Future<_i14.DialogResponse<dynamic>?>.value(),
      ) as _i16.Future<_i14.DialogResponse<dynamic>?>);
  @override
  _i16.Future<_i14.DialogResponse<T>?> showCustomDialog<T, R>({
    dynamic variant,
    String? title,
    String? description,
    bool? hasImage = false,
    String? imageUrl,
    bool? showIconInMainButton = false,
    String? mainButtonTitle,
    bool? showIconInSecondaryButton = false,
    String? secondaryButtonTitle,
    bool? showIconInAdditionalButton = false,
    String? additionalButtonTitle,
    bool? takesInput = false,
    _i17.Color? barrierColor = const _i17.Color(2315255808),
    bool? barrierDismissible = false,
    String? barrierLabel = r'',
    bool? useSafeArea = true,
    dynamic customData,
    R? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showCustomDialog,
          [],
          {
            #variant: variant,
            #title: title,
            #description: description,
            #hasImage: hasImage,
            #imageUrl: imageUrl,
            #showIconInMainButton: showIconInMainButton,
            #mainButtonTitle: mainButtonTitle,
            #showIconInSecondaryButton: showIconInSecondaryButton,
            #secondaryButtonTitle: secondaryButtonTitle,
            #showIconInAdditionalButton: showIconInAdditionalButton,
            #additionalButtonTitle: additionalButtonTitle,
            #takesInput: takesInput,
            #barrierColor: barrierColor,
            #barrierDismissible: barrierDismissible,
            #barrierLabel: barrierLabel,
            #useSafeArea: useSafeArea,
            #customData: customData,
            #data: data,
          },
        ),
        returnValue: _i16.Future<_i14.DialogResponse<T>?>.value(),
        returnValueForMissingStub: _i16.Future<_i14.DialogResponse<T>?>.value(),
      ) as _i16.Future<_i14.DialogResponse<T>?>);
  @override
  _i16.Future<_i14.DialogResponse<dynamic>?> showConfirmationDialog({
    String? title,
    String? description,
    String? cancelTitle = r'Cancel',
    _i17.Color? cancelTitleColor,
    String? confirmationTitle = r'Ok',
    _i17.Color? confirmationTitleColor,
    bool? barrierDismissible = false,
    _i14.DialogPlatform? dialogPlatform,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showConfirmationDialog,
          [],
          {
            #title: title,
            #description: description,
            #cancelTitle: cancelTitle,
            #cancelTitleColor: cancelTitleColor,
            #confirmationTitle: confirmationTitle,
            #confirmationTitleColor: confirmationTitleColor,
            #barrierDismissible: barrierDismissible,
            #dialogPlatform: dialogPlatform,
          },
        ),
        returnValue: _i16.Future<_i14.DialogResponse<dynamic>?>.value(),
        returnValueForMissingStub:
            _i16.Future<_i14.DialogResponse<dynamic>?>.value(),
      ) as _i16.Future<_i14.DialogResponse<dynamic>?>);
  @override
  void completeDialog(_i14.DialogResponse<dynamic>? response) =>
      super.noSuchMethod(
        Invocation.method(
          #completeDialog,
          [response],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PlayerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerService extends _i1.Mock implements _i18.PlayerService {
  @override
  _i2.PlayerRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlayerRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakePlayerRepositoryImpl_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PlayerRepositoryImpl);
  @override
  _i16.Future<List<_i3.PlayerModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i16.Future<List<_i3.PlayerModel>>.value(<_i3.PlayerModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i3.PlayerModel>>.value(<_i3.PlayerModel>[]),
      ) as _i16.Future<List<_i3.PlayerModel>>);
  @override
  _i16.Future<_i3.PlayerModel?> get(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i3.PlayerModel?>.value(),
        returnValueForMissingStub: _i16.Future<_i3.PlayerModel?>.value(),
      ) as _i16.Future<_i3.PlayerModel?>);
  @override
  _i16.Future<_i3.PlayerModel> put(_i3.PlayerModel? t) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue: _i16.Future<_i3.PlayerModel>.value(_FakePlayerModel_1(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i3.PlayerModel>.value(_FakePlayerModel_1(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i3.PlayerModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [FormationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFormationService extends _i1.Mock implements _i20.FormationService {
  @override
  _i4.FormationRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeFormationRepositoryImpl_2(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeFormationRepositoryImpl_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.FormationRepositoryImpl);
  @override
  _i16.Future<List<_i5.FormationModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i16.Future<List<_i5.FormationModel>>.value(<_i5.FormationModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i5.FormationModel>>.value(<_i5.FormationModel>[]),
      ) as _i16.Future<List<_i5.FormationModel>>);
  @override
  _i16.Future<_i5.FormationModel?> get(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i5.FormationModel?>.value(),
        returnValueForMissingStub: _i16.Future<_i5.FormationModel?>.value(),
      ) as _i16.Future<_i5.FormationModel?>);
  @override
  _i16.Future<_i5.FormationModel> put(_i5.FormationModel? t) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue:
            _i16.Future<_i5.FormationModel>.value(_FakeFormationModel_3(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i5.FormationModel>.value(_FakeFormationModel_3(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i5.FormationModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [TeamService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTeamService extends _i1.Mock implements _i21.TeamService {
  @override
  _i6.TeamRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTeamRepositoryImpl_4(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeTeamRepositoryImpl_4(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i6.TeamRepositoryImpl);
  @override
  _i16.Future<List<_i7.TeamModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i16.Future<List<_i7.TeamModel>>.value(<_i7.TeamModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i7.TeamModel>>.value(<_i7.TeamModel>[]),
      ) as _i16.Future<List<_i7.TeamModel>>);
  @override
  _i16.Future<_i7.TeamModel?> get(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i7.TeamModel?>.value(),
        returnValueForMissingStub: _i16.Future<_i7.TeamModel?>.value(),
      ) as _i16.Future<_i7.TeamModel?>);
  @override
  _i16.Future<_i7.TeamModel> put(_i7.TeamModel? t) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue: _i16.Future<_i7.TeamModel>.value(_FakeTeamModel_5(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i7.TeamModel>.value(_FakeTeamModel_5(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i7.TeamModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [PatternOfPlayService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPatternOfPlayService extends _i1.Mock
    implements _i22.PatternOfPlayService {
  @override
  _i8.PatternOfPlayRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePatternOfPlayRepositoryImpl_6(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakePatternOfPlayRepositoryImpl_6(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i8.PatternOfPlayRepositoryImpl);
  @override
  _i16.Future<List<_i9.PatternOfPlayModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i16.Future<List<_i9.PatternOfPlayModel>>.value(
            <_i9.PatternOfPlayModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i9.PatternOfPlayModel>>.value(
                <_i9.PatternOfPlayModel>[]),
      ) as _i16.Future<List<_i9.PatternOfPlayModel>>);
  @override
  _i16.Future<_i9.PatternOfPlayModel?> get(_i19.Uuid? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i9.PatternOfPlayModel?>.value(),
        returnValueForMissingStub: _i16.Future<_i9.PatternOfPlayModel?>.value(),
      ) as _i16.Future<_i9.PatternOfPlayModel?>);
  @override
  _i16.Future<_i9.PatternOfPlayModel> put(_i9.PatternOfPlayModel? t) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue:
            _i16.Future<_i9.PatternOfPlayModel>.value(_FakePatternOfPlayModel_7(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i9.PatternOfPlayModel>.value(_FakePatternOfPlayModel_7(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i9.PatternOfPlayModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [ConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigService extends _i1.Mock implements _i23.ConfigService {
  @override
  _i10.ConfigRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeConfigRepositoryImpl_8(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakeConfigRepositoryImpl_8(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i10.ConfigRepositoryImpl);
  @override
  _i16.Future<List<_i11.ConfigModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i16.Future<List<_i11.ConfigModel>>.value(<_i11.ConfigModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i11.ConfigModel>>.value(<_i11.ConfigModel>[]),
      ) as _i16.Future<List<_i11.ConfigModel>>);
  @override
  _i16.Future<_i11.ConfigModel?> get(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i11.ConfigModel?>.value(),
        returnValueForMissingStub: _i16.Future<_i11.ConfigModel?>.value(),
      ) as _i16.Future<_i11.ConfigModel?>);
  @override
  _i16.Future<_i11.ConfigModel> put(_i11.ConfigModel? t) => (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue: _i16.Future<_i11.ConfigModel>.value(_FakeConfigModel_9(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub:
            _i16.Future<_i11.ConfigModel>.value(_FakeConfigModel_9(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i11.ConfigModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}

/// A class which mocks [PlayerContractService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerContractService extends _i1.Mock
    implements _i24.PlayerContractService {
  @override
  _i12.PlayerContractRepositoryImpl get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlayerContractRepositoryImpl_10(
          this,
          Invocation.getter(#repository),
        ),
        returnValueForMissingStub: _FakePlayerContractRepositoryImpl_10(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i12.PlayerContractRepositoryImpl);
  @override
  _i16.Future<List<_i13.PlayerContractModel>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i16.Future<List<_i13.PlayerContractModel>>.value(
            <_i13.PlayerContractModel>[]),
        returnValueForMissingStub:
            _i16.Future<List<_i13.PlayerContractModel>>.value(
                <_i13.PlayerContractModel>[]),
      ) as _i16.Future<List<_i13.PlayerContractModel>>);
  @override
  _i16.Future<_i13.PlayerContractModel?> get(_i19.Uuid? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i16.Future<_i13.PlayerContractModel?>.value(),
        returnValueForMissingStub:
            _i16.Future<_i13.PlayerContractModel?>.value(),
      ) as _i16.Future<_i13.PlayerContractModel?>);
  @override
  _i16.Future<_i13.PlayerContractModel> put(_i13.PlayerContractModel? t) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [t],
        ),
        returnValue: _i16.Future<_i13.PlayerContractModel>.value(
            _FakePlayerContractModel_11(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
        returnValueForMissingStub: _i16.Future<_i13.PlayerContractModel>.value(
            _FakePlayerContractModel_11(
          this,
          Invocation.method(
            #put,
            [t],
          ),
        )),
      ) as _i16.Future<_i13.PlayerContractModel>);
  @override
  _i16.Future<bool> delete(_i19.Uuid? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i16.Future<bool>.value(false),
        returnValueForMissingStub: _i16.Future<bool>.value(false),
      ) as _i16.Future<bool>);
}
