enum SoccerPositionEnum {
  goalkeeper,
  centerBack,
  rightBack,
  leftBack,
  wingBack,
  sweeper,
  defensiveMidfielder,
  centralMidfielder,
  attackingMidfielder,
  rightMidfielder,
  leftMidfielder,
  rightWinger,
  leftWinger,
  forward,
  striker,
}
